name: Deploy Fooseshoes

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code (store repo)
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Astro project
        run: pnpm run build

      - name: Deploy to target repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.TARGET_REPO_TOKEN }}
          external_repository: luxors/portfolio
          publish_branch: main
          publish_dir: ./dist
          destination_dir: fooseshoes
          keep_files: true
